<div class="page-head"><div><h1>有給管理（管理者）</h1><p class="muted">付与・残数調整・全社員の予定確認ができます。</p></div><a class="button" href="<?= e(url('admin')) ?>">管理トップ</a></div>
<section class="panel"><div class="section-head"><div><h2>有給承認フロー</h2><p class="muted">有効時は社員の登録が「承認待ち」になります。無効化すると現在の承認待ちはすべて通常登録へ移ります。</p></div><span class="tag"><?= $approvalRequired ? '有効' : '無効' ?></span></div><form method="post" action="<?= e(url('admin/settings/approval')) ?>" data-confirm="承認フローの設定を変更しますか？"><?= \App\Csrf::field() ?><input type="hidden" name="enabled" value="<?= $approvalRequired ? '0' : '1' ?>"><button class="<?= $approvalRequired ? 'danger' : 'primary' ?>"><?= $approvalRequired ? '承認フローを無効にする' : '承認フローを有効にする' ?></button></form></section>

<h2 class="section-title">初期データ移行</h2>
<section class="panel">
  <div class="section-head"><div><h2>有給残数をCSVから取り込む</h2><p class="muted">氏名で社員を照合し、運用開始時点の残数を付与データとして登録します。取り込み前に内容を確認できます。</p></div><a class="button small" href="<?= e(url('admin/leave/import/template')) ?>">見本CSVをダウンロード</a></div>
  <p class="notice">現在使用中の「有給使用状況」の月別CSVは、そのまま読み込めます。現在月の残数と更新月から取り込み内容を自動計算します。同姓同名がいる場合は安全のためエラーになります。</p>
  <form method="post" action="<?= e(url('admin/leave/import/preview')) ?>" enctype="multipart/form-data" class="import-upload">
    <?= \App\Csrf::field() ?><input type="hidden" name="MAX_FILE_SIZE" value="1048576">
    <input type="file" name="csv_file" accept=".csv,text/csv" required><button class="primary">CSVを読み込む</button>
  </form>
  <?php if ($importPreview): ?>
    <div class="import-preview">
      <div class="section-head"><div><h2>取り込み内容の確認</h2><p class="muted"><?= e($importPreview['source_name']) ?> ／ <?= e($importPreview['source_format'] ?? '') ?><?= !empty($importPreview['as_of']) ? ' ／ '.e($importPreview['as_of']).'時点' : '' ?><br>新規 <?= (int)$importPreview['valid_count'] ?>件・スキップ <?= (int)($importPreview['skip_count'] ?? 0) ?>件・重複 <?= (int)$importPreview['duplicate_count'] ?>件・エラー <?= (int)$importPreview['error_count'] ?>件</p></div></div>
      <div class="table-wrap"><table><thead><tr><th>行</th><th>社員</th><th>内訳</th><th>付与年</th><th>残日数</th><th>前借</th><th>付与日</th><th>有効期限</th><th>判定</th></tr></thead><tbody>
        <?php foreach (array_slice($importPreview['rows'], 0, 200) as $row): ?><tr>
          <td><?= (int)$row['line'] ?></td><td><?= e($row['employee_name'] ?: $row['employee_code']) ?></td><td><strong><?= e($row['balance_type'] ?? '移行残数') ?></strong></td><td><?= e($row['grant_year']) ?></td><td><?= number_format((float)($row['remaining_days'] ?? $row['days']), 1) ?>日</td><td><?php if ((float)($row['advance_days'] ?? 0) > 0): ?><span class="tag danger-tag"><?= number_format((float)$row['advance_days'], 1) ?>日</span><?php else: ?>—<?php endif; ?></td><td><?= e($row['granted_on']) ?></td><td><?= e($row['expires_on']) ?></td>
          <td><?php if ($row['errors']): ?><span class="tag danger-tag"><?= e(implode('／', $row['errors'])) ?></span><?php elseif (!empty($row['skip_reason'])): ?><span class="tag"><?= e($row['skip_reason']) ?></span><?php elseif ($row['duplicate']): ?><span class="tag">重複・スキップ</span><?php else: ?><span class="tag success-tag">取り込み対象</span><?php endif; ?></td>
        </tr><?php endforeach; ?>
      </tbody></table></div>
      <?php if (count($importPreview['rows']) > 200): ?><p class="muted">画面には先頭200行まで表示しています。</p><?php endif; ?>
      <div class="row-actions">
        <?php if ((int)$importPreview['error_count'] === 0 && (int)$importPreview['valid_count'] > 0): ?><form method="post" action="<?= e(url('admin/leave/import/confirm')) ?>" data-confirm="表示されている有給残数を取り込みますか？"><?= \App\Csrf::field() ?><button class="primary">この内容で取り込む</button></form><?php endif; ?>
        <form method="post" action="<?= e(url('admin/leave/import/cancel')) ?>"><?= \App\Csrf::field() ?><button>確認を取り消す</button></form>
      </div>
      <?php if ((int)$importPreview['error_count'] > 0): ?><p class="flash error">エラー行があります。CSVを修正して、もう一度読み込んでください。</p><?php endif; ?>
    </div>
  <?php endif; ?>
</section>
<section class="panel"><h2>社員別残数</h2><div class="table-wrap"><table><thead><tr><th>社員</th><th>前年繰越</th><th>今年付与</th><th>現在残数</th><th>予定</th><th>予定反映後</th></tr></thead><tbody><?php foreach($employees as $employee): ?><tr><td><?= e($employee['full_name']) ?></td><td><?= number_format($employee['summary']['previous_year'],1) ?>日</td><td><?= number_format($employee['summary']['current_year'],1) ?>日</td><td><?= number_format($employee['summary']['current'],1) ?>日</td><td><?= number_format($employee['summary']['scheduled'],1) ?>日</td><td><strong><?= number_format($employee['summary']['forecast'],1) ?>日</strong></td></tr><?php endforeach; ?></tbody></table></div><p class="muted">今年付与分から先に消化し、残った分は翌年度へ繰り越せます。</p></section>
<section class="panel"><h2>代理で有給予定を登録</h2><p class="notice">本人と上長の事前確認が済んでいることを確認して登録してください。</p><form method="post" action="<?= e(url('admin/leave/create')) ?>" class="grid-form"><?= \App\Csrf::field() ?><label>社員<select name="employee_id"><?php foreach($employees as $employee): ?><option value="<?= (int)$employee['id'] ?>"><?= e($employee['full_name']) ?></option><?php endforeach; ?></select></label><label>取得日<input type="date" name="leave_date" required></label><label>取得区分<select name="leave_type"><option value="full">1日</option><option value="am">午前休</option><option value="pm">午後休</option></select></label><label>事前確認相手<input name="confirmed_with"></label><label>連絡事項<input name="note"></label><button class="primary">代理登録する</button></form></section>
<div class="two-col"><section class="panel"><h2>有給付与</h2><p class="muted">有効期限は付与日の2年後の前日まで指定できます。</p><form method="post" action="<?= e(url('admin/leave/grant')) ?>"><?= \App\Csrf::field() ?><label>社員<select name="employee_id"><?php foreach($employees as $employee): ?><option value="<?= (int)$employee['id'] ?>"><?= e($employee['full_name']) ?></option><?php endforeach; ?></select></label><label>付与年<select name="grant_year"><option value="<?= date('Y') ?>"><?= date('Y') ?>年付与分</option><option value="<?= date('Y')-1 ?>"><?= date('Y')-1 ?>年付与分</option><option value="<?= date('Y')-2 ?>"><?= date('Y')-2 ?>年付与分</option></select></label><div class="field-row"><label>付与日<input type="date" name="granted_on" required></label><label>付与日数<input type="number" name="days" min="0.5" step="0.5" required></label></div><label>有効期限<input type="date" name="expires_on" required></label><label>付与理由<input name="reason" placeholder="定期付与、移行残高など" required></label><button class="primary">付与する</button></form></section>
<section class="panel"><h2>残数調整</h2><form method="post" action="<?= e(url('admin/leave/adjust')) ?>"><?= \App\Csrf::field() ?><label>社員<select name="employee_id"><?php foreach($employees as $employee): ?><option value="<?= (int)$employee['id'] ?>"><?= e($employee['full_name']) ?></option><?php endforeach; ?></select></label><label>付与年<select name="grant_year"><option value="<?= date('Y') ?>"><?= date('Y') ?>年付与分</option><option value="<?= date('Y')-1 ?>"><?= date('Y')-1 ?>年付与分</option><option value="<?= date('Y')-2 ?>"><?= date('Y')-2 ?>年付与分</option></select></label><label>増減日数<input type="number" name="days_delta" step="0.5" placeholder="例: -0.5 または 1.0" required></label><label>調整理由<textarea name="reason" required></textarea></label><button class="primary">調整する</button></form></section></div>
<section class="panel"><h2>有給予定・履歴</h2><div class="table-wrap"><table><thead><tr><th>取得日</th><th>社員</th><th>区分</th><th>状態</th><th>承認・取消</th></tr></thead><tbody><?php $leaveLabels=['pending'=>'承認待ち','approved'=>'承認済み','registered'=>'登録済み','taken'=>'取得済み','rejected'=>'却下','cancelled'=>'取消済み']; foreach($entries as $entry): ?><tr><td><?= e($entry['leave_date']) ?></td><td><?= e($entry['full_name']) ?></td><td><?= e(['full'=>'1日','am'=>'午前休','pm'=>'午後休'][$entry['leave_type']]) ?></td><td><span class="tag"><?= e($leaveLabels[$entry['status']] ?? $entry['status']) ?></span><?php if($entry['status']==='rejected'): ?><small><?= e($entry['rejection_reason']) ?></small><?php endif; ?></td><td><?php if($entry['status']==='pending'): ?><div class="row-actions"><form method="post" action="<?= e(url('admin/leave/review')) ?>" class="inline-form"><?= \App\Csrf::field() ?><input type="hidden" name="entry_id" value="<?= (int)$entry['id'] ?>"><input type="hidden" name="decision" value="approve"><button class="primary small">承認</button></form><form method="post" action="<?= e(url('admin/leave/review')) ?>" class="inline-form"><?= \App\Csrf::field() ?><input type="hidden" name="entry_id" value="<?= (int)$entry['id'] ?>"><input type="hidden" name="decision" value="reject"><input name="reason" placeholder="却下理由" required><button class="danger small">却下</button></form></div><?php elseif(!in_array($entry['status'],['cancelled','rejected'],true)): ?><form method="post" action="<?= e(url('admin/leave/cancel')) ?>" class="inline-form" data-confirm="管理者として取り消しますか？"><?= \App\Csrf::field() ?><input type="hidden" name="entry_id" value="<?= (int)$entry['id'] ?>"><input name="reason" placeholder="訂正・取消理由" required><button class="danger small">取消</button></form><?php else: ?><?= e($entry['cancellation_reason'] ?: $entry['rejection_reason']) ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></section>

<h2 class="section-title">代休</h2>
<section class="panel"><h2>社員別代休残数</h2><div class="table-wrap"><table><thead><tr><th>社員</th><th>現在残数</th><th>取得予定</th><th>取得可能</th></tr></thead><tbody><?php foreach($employees as $employee): ?><tr><td><?= e($employee['full_name']) ?></td><td><?= number_format($employee['comp_summary']['current'],1) ?>日</td><td><?= number_format($employee['comp_summary']['scheduled'],1) ?>日</td><td><strong><?= number_format($employee['comp_summary']['available'],1) ?>日</strong></td></tr><?php endforeach; ?></tbody></table></div></section>
<div class="two-col"><section class="panel"><h2>代休発生状況</h2><p class="muted">休日出勤の登録で自動発生します。訂正・取消時はここで発生を取り消します。</p><div class="table-wrap"><table><thead><tr><th>発生日</th><th>社員</th><th>有効期限</th><th>状態</th><th>発生取消</th></tr></thead><tbody><?php foreach($compGrants as $grant): ?><tr><td><?= e($grant['occurred_on']) ?></td><td><?= e($grant['full_name']) ?></td><td><?= e($grant['expires_on']) ?></td><td><span class="tag"><?= $grant['status']==='cancelled'?'取消済み':'有効' ?></span></td><td><?php if($grant['status']!=='cancelled'): ?><form method="post" action="<?= e(url('admin/comp-leave/grant-cancel')) ?>" class="inline-form" data-confirm="この代休発生を取り消しますか？"><?= \App\Csrf::field() ?><input type="hidden" name="grant_id" value="<?= (int)$grant['id'] ?>"><input name="reason" placeholder="訂正・取消理由" required><button class="danger small">取消</button></form><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?><?php if(!$compGrants): ?><tr><td colspan="5" class="empty">代休の発生はありません。</td></tr><?php endif; ?></tbody></table></div></section>
<section class="panel"><h2>代休取得・履歴</h2><div class="table-wrap"><table><thead><tr><th>取得日</th><th>社員</th><th>状態</th></tr></thead><tbody><?php foreach($compEntries as $entry): ?><tr><td><?= e($entry['leave_date']) ?></td><td><?= e($entry['full_name']) ?></td><td><?= $entry['status']==='cancelled'?'取消済み':($entry['leave_date']<date('Y-m-d')?'取得済み':'登録済み') ?><?php if($entry['status']==='cancelled'): ?> <small><?= e($entry['cancellation_reason']) ?></small><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$compEntries): ?><tr><td colspan="3" class="empty">代休の取得はありません。</td></tr><?php endif; ?></tbody></table></div></section></div>
